"""
Django settings for zooper_matching project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '04qx*&q)g*7mi(h&vuthyrv0d0cx=6%oj%dbl9!!_rwgzlz_(r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'accounts',
    'common',
    'matching',
    'producto',
    'supermercado',
    'supermercado.jumbo',
    'supermercado.lider',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zooper_matching.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # >= 1.8
            ],
        },
    },
]

WSGI_APPLICATION = 'zooper_matching.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',  # postgresql, mysql, sqlite3, oracle
        'NAME': 'zooper_matching',  # os.path.join(BASE_DIR, 'db.sqlite3'),
        'USER': 'zooper',
        'PASSWORD': 'asdf1234',
        'HOST': '127.0.0.1',  # 127.0.0.1, localhost, ...
        'PORT': '5432',  # 3306 (mysql), 5432 (postgresql), ...
        # The lifetime of a database connection, in seconds.
        # Use 0 to close database connections at the end of each request
        # (Django's historical behavior)
        # and None for unlimited persistent connections.
        'CONN_MAX_AGE': 0,
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-ES'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


STATIC_ROOT = '/var/www/html/zooper/static'

STATICFILES_DIRS = (
    # C:\PythonProjects\proyecto-django\proyecto\
    os.path.join(BASE_DIR, 'static'),
    ('matching', os.path.join(BASE_DIR, 'matching', 'static')),
    ('common', os.path.join(BASE_DIR, 'common', 'static')),
    ('accounts', os.path.join(BASE_DIR, 'accounts', 'static')),
    ('producto', os.path.join(BASE_DIR, 'producto', 'static')),
    ('supermercado', os.path.join(BASE_DIR, 'supermercado', 'static')),
    ('supermercado.jumbo', os.path.join(BASE_DIR, 'supermercado\jumbo', 'static')),
    ('supermercado.lider', os.path.join(BASE_DIR, 'supermercado\lider', 'static')),
)



STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
)

"""
STATICFILES_DIRS = (
    os.path.join(PROJECT_PATH, 'project_static'),
    ('my_app', os.path.join(PROJECT_PATH, 'my_app', 'static')),
    ('another_app', os.path.join(PROJECT_PATH, 'another_app', 'static')),
    ...
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
)
"""



MEDIA_URL = '/media/'

MEDIA_ROOT = '/var/www/html/zooper/media'