# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0002_auto_20181012_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsupermercado',
            name='modelo_id',
            field=models.IntegerField(default=0),
        ),
    ]
