# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0003_logsupermercado_modelo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsupermercado',
            name='tipo',
            field=models.CharField(choices=[('NUMERO', 'NUMERO'), ('DECIMAL', 'DECIMAL'), ('TEXTO', 'TEXTO'), ('JSON', 'JSON'), ('FECHA', 'FECHA')], max_length=30, null=True),
        ),
    ]
