# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0004_auto_20181018_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsupermercado',
            name='grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='logsupermercado',
            name='status',
            field=models.CharField(choices=[('ALERTA', 'ALERTA'), ('ERROR', 'ERROR'), ('INFO', 'INFO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logsupermercado',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
