# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0005_auto_20181025_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsupermercado',
            name='modelo_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
