# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0007_articulolider_infoactualizacionarticulolider_infobusquedaarticulolider'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='infoactualizacionarticulolider',
        #     name='articulolider',
        # ),
        migrations.DeleteModel(
            name='InfoBusquedaArticuloLider',
        ),
        migrations.DeleteModel(
            name='ArticuloLider',
        ),
        migrations.DeleteModel(
            name='InfoActualizacionArticuloLider',
        ),
    ]
