# -*- coding: utf-8 -*-
from __future__ import unicode_literals


OK = 'OK'
ERROR = 'ERROR'
DESHABILITADO = 'DESHABILITADO'

ESTADOS_PRODUCTO = (
    (OK, 'OK'),
    (ERROR, 'ERROR'),
    (DESHABILITADO, 'DESHABILITADO'),
)


NO_ACTUALIZADO = 'NO_ACTUALIZADO'
ACTUALIZADO = 'ACTUALIZADO'
PENDIENTE_ACTUALIZACION = 'PENDIENTE_ACTUALIZACION'
ERROR = 'ERROR'

ESTADOS_ACTUALIZACION = (
    (NO_ACTUALIZADO, 'NO_ACTUALIZADO'),
    (ACTUALIZADO, 'ACTUALIZADO'),
    (PENDIENTE_ACTUALIZACION, 'PENDIENTE_ACTUALIZACION'),
    (ERROR, 'ERROR'),
)

ENCONTRADO = 'ENCONTRADO'
EN_PROCESO = 'EN_PROCESO'
NO_ENCONTRADO = 'NO_ENCONTRADO'


ESTADOS_BUSQUEDA = (
    (ENCONTRADO, 'ENCONTRADO'),
    (EN_PROCESO, 'EN_PROCESO'),
    (NO_ENCONTRADO, 'NO_ENCONTRADO'),
)