# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 02:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloJumbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.CharField(max_length=20, null=True)),
                ('codigo_referencia', models.CharField(max_length=20, null=True)),
                ('item_id', models.CharField(max_length=20, null=True)),
                ('ean', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=300, null=True)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('url_imagen', models.CharField(max_length=200, null=True)),
                ('url_producto', models.CharField(max_length=200, null=True)),
                ('data_producto', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_sku', django.contrib.postgres.fields.jsonb.JSONField()),
                ('precio', models.IntegerField(default=0)),
                ('precio_sin_descuento', models.IntegerField(default=0)),
                ('validez_precio', models.DateTimeField(auto_now_add=True)),
                ('cantidad_disponible', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PromocionJumbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitada', models.BooleanField(default=False)),
                ('promocion_id', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('grupo', models.CharField(max_length=200, null=True)),
                ('tipo', models.CharField(max_length=200, null=True)),
                ('tipo_descuento', models.CharField(max_length=200, null=True)),
                ('tipo_promocion', models.CharField(max_length=200, null=True)),
                ('valor', models.CharField(max_length=200, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_final', models.DateTimeField(auto_now_add=True)),
                ('dias_disponible', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_afectada', models.IntegerField(default=0)),
            ],
        ),
    ]
