# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumbo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoActualizacionArticuloJumbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificado_busqueda', models.CharField(max_length=20, null=True)),
                ('estado', models.CharField(choices=[('NO_ACTUALIZADO', 'NO_ACTUALIZADO'), ('ACTUALIZADO', 'ACTUALIZADO'), ('PENDIENTE_ACTUALIZACION', 'PENDIENTE_ACTUALIZACION'), ('ERROR', 'ERROR')], max_length=30, null=True)),
                ('estado_mensaje', models.CharField(max_length=100, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='articulojumbo',
            name='estado',
            field=models.CharField(choices=[('OK', 'OK'), ('ERROR', 'ERROR'), ('DESHABILITADO', 'DESHABILITADO')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articulojumbo',
            name='estado_mensaje',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promocionjumbo',
            name='estado',
            field=models.CharField(choices=[('OK', 'OK'), ('ERROR', 'ERROR'), ('DESHABILITADO', 'DESHABILITADO')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='promocionjumbo',
            name='estado_mensaje',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infoactualizacionarticulojumbo',
            name='articulojumbo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jumbo.ArticuloJumbo'),
        ),
    ]
