# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumbo', '0003_auto_20181016_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoactualizacionarticulojumbo',
            old_name='identificado_busqueda',
            new_name='identificador_busqueda',
        ),
    ]
