# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 09:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumbo', '0005_infobusquedaarticulojumbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulojumbo',
            name='data_producto',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='articulojumbo',
            name='data_sku',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='promocionjumbo',
            name='dias_disponible',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
