# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbo', '0006_auto_20181107_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocionjumbo',
            name='cantidad',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='promocionjumbo',
            name='cantidad_afectada',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
