# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productojumbo',
            name='estado_actualizacion',
            field=models.CharField(choices=[('no_actualizada', 'No actualizada'), ('actualizada', 'actualizada'), ('pendiente', 'pendiente')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productojumbo',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 9, 37, 18, 110334)),
        ),
        migrations.AddField(
            model_name='productolider',
            name='estado_actualizacion',
            field=models.CharField(choices=[('no_actualizada', 'No actualizada'), ('actualizada', 'actualizada'), ('pendiente', 'pendiente')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productolider',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 9, 37, 18, 109442)),
        ),
        migrations.AddField(
            model_name='productotelemercado',
            name='estado_actualizacion',
            field=models.CharField(choices=[('no_actualizada', 'No actualizada'), ('actualizada', 'actualizada'), ('pendiente', 'pendiente')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productotelemercado',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 9, 37, 18, 111104)),
        ),
        migrations.AddField(
            model_name='productotottus',
            name='estado_actualizacion',
            field=models.CharField(choices=[('no_actualizada', 'No actualizada'), ('actualizada', 'actualizada'), ('pendiente', 'pendiente')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productotottus',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 9, 37, 18, 111986)),
        ),
    ]
