# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 01:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20180925_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productolider',
            name='estado_actualizacion',
        ),
        migrations.AddField(
            model_name='productolider',
            name='estado',
            field=models.CharField(choices=[('NO ACTUALIZADO', 'NO ACTUALIZADO'), ('ACTUALIZADA', 'ACTUALIZADA'), ('PENDIENTE ACTUALIZACION', 'PENDIENTE ACTUALIZACION'), ('ERROR_PRECIO', 'ERROR_PRECIO'), ('SIN_PRECIO', 'SIN_PRECIO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productojumbo',
            name='estado_actualizacion',
            field=models.CharField(choices=[('NO ACTUALIZADO', 'NO ACTUALIZADO'), ('ACTUALIZADA', 'ACTUALIZADA'), ('PENDIENTE ACTUALIZACION', 'PENDIENTE ACTUALIZACION'), ('ERROR_PRECIO', 'ERROR_PRECIO'), ('SIN_PRECIO', 'SIN_PRECIO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productojumbo',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 22, 45, 26, 533597)),
        ),
        migrations.AlterField(
            model_name='productolider',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 22, 45, 26, 531485)),
        ),
        migrations.AlterField(
            model_name='productotelemercado',
            name='estado_actualizacion',
            field=models.CharField(choices=[('NO ACTUALIZADO', 'NO ACTUALIZADO'), ('ACTUALIZADA', 'ACTUALIZADA'), ('PENDIENTE ACTUALIZACION', 'PENDIENTE ACTUALIZACION'), ('ERROR_PRECIO', 'ERROR_PRECIO'), ('SIN_PRECIO', 'SIN_PRECIO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productotelemercado',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 22, 45, 26, 535452)),
        ),
        migrations.AlterField(
            model_name='productotottus',
            name='estado_actualizacion',
            field=models.CharField(choices=[('NO ACTUALIZADO', 'NO ACTUALIZADO'), ('ACTUALIZADA', 'ACTUALIZADA'), ('PENDIENTE ACTUALIZACION', 'PENDIENTE ACTUALIZACION'), ('ERROR_PRECIO', 'ERROR_PRECIO'), ('SIN_PRECIO', 'SIN_PRECIO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productotottus',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 22, 45, 26, 537535)),
        ),
    ]
