# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20180927_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productojumbo',
            old_name='estado_actualizacion',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='productotelemercado',
            old_name='estado_actualizacion',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='productotottus',
            old_name='estado_actualizacion',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='productojumbo',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 22, 46, 11, 815702)),
        ),
        migrations.AlterField(
            model_name='productolider',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 22, 46, 11, 814832)),
        ),
        migrations.AlterField(
            model_name='productotelemercado',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 22, 46, 11, 816469)),
        ),
        migrations.AlterField(
            model_name='productotottus',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 22, 46, 11, 817330)),
        ),
    ]
