# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20180927_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotelemercado',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='productojumbo',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 23, 4, 38, 942326)),
        ),
        migrations.AlterField(
            model_name='productolider',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 23, 4, 38, 941459)),
        ),
        migrations.AlterField(
            model_name='productotelemercado',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 23, 4, 38, 943101)),
        ),
        migrations.AlterField(
            model_name='productotottus',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 23, 4, 38, 943924)),
        ),
    ]
