# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20180927_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productojumbo',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 23, 4, 51, 795073)),
        ),
        migrations.AlterField(
            model_name='productolider',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 23, 4, 51, 792882)),
        ),
        migrations.AlterField(
            model_name='productotelemercado',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 23, 4, 51, 797194)),
        ),
        migrations.AlterField(
            model_name='productotottus',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 23, 4, 51, 799629)),
        ),
    ]
