# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20180927_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productojumbo',
            name='estado',
            field=models.CharField(choices=[('NO_ACTUALIZADO', 'NO_ACTUALIZADO'), ('ACTUALIZADA', 'ACTUALIZADA'), ('PENDIENTE_ACTUALIZACION', 'PENDIENTE_ACTUALIZACION'), ('ERROR', 'ERROR'), ('ERROR_PRECIO', 'ERROR_PRECIO'), ('SIN_PRECIO', 'SIN_PRECIO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productojumbo',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 23, 5, 45, 779327)),
        ),
        migrations.AlterField(
            model_name='productolider',
            name='estado',
            field=models.CharField(choices=[('NO_ACTUALIZADO', 'NO_ACTUALIZADO'), ('ACTUALIZADA', 'ACTUALIZADA'), ('PENDIENTE_ACTUALIZACION', 'PENDIENTE_ACTUALIZACION'), ('ERROR', 'ERROR'), ('ERROR_PRECIO', 'ERROR_PRECIO'), ('SIN_PRECIO', 'SIN_PRECIO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productolider',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 23, 5, 45, 778427)),
        ),
        migrations.AlterField(
            model_name='productotelemercado',
            name='estado',
            field=models.CharField(choices=[('NO_ACTUALIZADO', 'NO_ACTUALIZADO'), ('ACTUALIZADA', 'ACTUALIZADA'), ('PENDIENTE_ACTUALIZACION', 'PENDIENTE_ACTUALIZACION'), ('ERROR', 'ERROR'), ('ERROR_PRECIO', 'ERROR_PRECIO'), ('SIN_PRECIO', 'SIN_PRECIO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productotelemercado',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 23, 5, 45, 780094)),
        ),
        migrations.AlterField(
            model_name='productotottus',
            name='estado',
            field=models.CharField(choices=[('NO_ACTUALIZADO', 'NO_ACTUALIZADO'), ('ACTUALIZADA', 'ACTUALIZADA'), ('PENDIENTE_ACTUALIZACION', 'PENDIENTE_ACTUALIZACION'), ('ERROR', 'ERROR'), ('ERROR_PRECIO', 'ERROR_PRECIO'), ('SIN_PRECIO', 'SIN_PRECIO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productotottus',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 23, 5, 45, 781213)),
        ),
    ]
