# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_auto_20181025_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productojumbo',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 19, 0, 51, 712177)),
        ),
        migrations.AlterField(
            model_name='productolider',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 19, 0, 51, 711009)),
        ),
        migrations.AlterField(
            model_name='productotelemercado',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 19, 0, 51, 713257)),
        ),
        migrations.AlterField(
            model_name='productotottus',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 19, 0, 51, 714429)),
        ),
    ]
